# Generated by Django 6.0.3 on 2026-03-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='paper_balance',
            field=models.DecimalField(decimal_places=2, default=100000.0, max_digits=15),
        ),
    ]
