# Generated by Django 6.0.3 on 2026-04-11 11:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['created_at']},
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['user', '-created_at'], name='market_chat_user_id_5d3b93_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['symbol'], name='market_news_symbol_9b2677_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['-published_at'], name='market_news_publish_8b6121_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['symbol', '-published_at'], name='market_news_symbol_de640d_idx'),
        ),
        migrations.AddIndex(
            model_name='paperholding',
            index=models.Index(fields=['user'], name='paper_holdi_user_id_2a5bb8_idx'),
        ),
        migrations.AddIndex(
            model_name='paperholding',
            index=models.Index(fields=['user', 'symbol'], name='paper_holdi_user_id_bd67fa_idx'),
        ),
        migrations.AddIndex(
            model_name='papertrade',
            index=models.Index(fields=['user', '-executed_at'], name='paper_trade_user_id_d8d540_idx'),
        ),
        migrations.AddIndex(
            model_name='papertrade',
            index=models.Index(fields=['user', 'symbol'], name='paper_trade_user_id_7f6b0c_idx'),
        ),
        migrations.AddIndex(
            model_name='papertrade',
            index=models.Index(fields=['user', 'trade_type'], name='paper_trade_user_id_8a9994_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['user'], name='market_port_user_id_a37cd0_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['user', 'symbol'], name='market_port_user_id_fbd68f_idx'),
        ),
        migrations.AddIndex(
            model_name='stockalert',
            index=models.Index(fields=['user', 'is_active'], name='market_stoc_user_id_b6cd5b_idx'),
        ),
        migrations.AddIndex(
            model_name='stockalert',
            index=models.Index(fields=['user', 'symbol'], name='market_stoc_user_id_2a60dc_idx'),
        ),
        migrations.AddIndex(
            model_name='stockalert',
            index=models.Index(fields=['symbol', 'is_active'], name='market_stoc_symbol_908d93_idx'),
        ),
        migrations.AddIndex(
            model_name='stockalert',
            index=models.Index(fields=['user', 'last_triggered_at'], name='market_stoc_user_id_bf19c8_idx'),
        ),
        migrations.AddIndex(
            model_name='watchlist',
            index=models.Index(fields=['user'], name='market_watc_user_id_fe48dd_idx'),
        ),
        migrations.AddIndex(
            model_name='watchlist',
            index=models.Index(fields=['user', 'symbol'], name='market_watc_user_id_2e5acc_idx'),
        ),
    ]
