# Generated by Django 6.0.3 on 2026-05-25 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_newsalertpreference_newssymbolalert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
