"""
Django settings for alphascope project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
from dotenv import load_dotenv
from decouple import config
import os

import smtplib

load_dotenv()
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")

ALPHA_VANTAGE_API_KEY = os.getenv("ALPHA_VANTAGE_API_KEY")
FINNHUB_API_KEY = os.getenv("FINNHUB_API_KEY")
GROQ_API_KEY = os.getenv("GROQ_API_KEY")

FRONTEND_URL = os.environ.get("FRONTEND_URL", "http://localhost:5173")
PASSWORD_RESET_CONFIRM_URL = "reset-password/{uid}/{token}"
AI_RECOMMEND_MAX_SYMBOLS = 10 
# Required by dj-rest-auth for email-based flows
SITE_ID = 1
 
# Optional: make tokens expire after 1 day (default is 3 days)
# from datetime import timedelta
# PASSWORD_RESET_TIMEOUT = 86400  # seconds

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-x@xd0&dv8a)nixe!la&w$+sa%3c8_5t4daw496m7ilu_mz1ie9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

CACHES = {
    "default": {
        "BACKEND":  "django.core.cache.backends.db.DatabaseCache",
        "LOCATION": "alphascope_cache",   # table name in your DB
    }
}

# Application definition

INSTALLED_APPS = [
    "daphne",   # ← must be first
    "channels",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'market',
    'rest_framework_simplejwt.token_blacklist',
    "django_extensions",
    "corsheaders",
    
]
AUTH_USER_MODEL = 'accounts.User'
MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "market.middleware.LatencyMiddleware",
]
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "https://alpha-scope-neon.vercel.app"
]
ASGI_APPLICATION = "alphascope.asgi.application"

# Free in-memory layer — no Redis needed for dev
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    },
}


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}


SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKEN':True,
}

ROOT_URLCONF = 'alphascope.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'alphascope.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'ALPHASCOPE_DB',
#         'USER':'root',
#         'PASSWORD':'admin@123',
#         'HOST':'localhost',
#         'PORT':'3306'
#     }
# }

ALLOWED_HOSTS = [
    'alphascope-4fa7.onrender.com',
    '127.0.0.1',
    'localhost'
]

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
# Celery settings
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'

# Windows fix
CELERY_WORKER_POOL = 'solo'


# Email settings 
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER ='alphascope.team@gmail.com'      # sender
EMAIL_HOST_PASSWORD = 'mklkcjtvbhsxvovj'

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# Email config (use Gmail or any SMTP)
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "alphascope.team@gmail.com"
EMAIL_HOST_PASSWORD = "mklkcjtvbhsxvovj"   # Gmail App Password, not your login password
DEFAULT_FROM_EMAIL = "AlphaScope <alphascope.team@gmail.com>"

# Frontend URL used in reset link
FRONTEND_URL = "http://localhost:5173"  # change to production URL when deploying
from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    "price-alert-check": {
        "task": "market.tasks.stock_alert_agent",
        "schedule": crontab(minute=0, hour="*"),  # ← every hour on the dot
    },
    "daily-news-digest": {
        "task": "market.tasks.stock_news_agent",
        "schedule": crontab(hour=8, minute=0),
    },
}



# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"
